# Generated by Django 5.2.6 on 2025-09-10 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_customer_store_custo_first_n_a7e990_idx_and_more'),
    ]

    operations = [
        migrations.RunSQL('''
        INSERT INTO store_collection(title) VALUES ('collection1')''','''
        DELETE FROM store_collection WHERE title='collection1'
        '''                                                    
        )
    ]
